### PR TITLE
Update FTPClient_Generic_Impl.h

### PR DESCRIPTION
**Pull request by MirkoAusFFM**
Good client, but please use the params uniformly. THX!

### CODE REVIEW

**Comment by khoih-prog** [comment]
HI @MirkoAusFFM 

Thanks for your best effort to make the PR, but I'm sorry you have to at least compile without error, before making PR.

For example, you also have to modify the declarations

https://github.com/khoih-prog/FTPClient_Generic/blob/918787a9efa453d7ac366d48a845058bd3032df0/src/FTPClient_Generic.hpp#L141

and

https://github.com/khoih-prog/FTPClient_Generic/blob/918787a9efa453d7ac366d48a845058bd3032df0/src/FTPClient_Generic.hpp#L146

to match the new mods.

If you have some more time, please also modify all possible declarations to be safe. I also suggest you to change all declarations to use **reference** to be more efficient.

Waiting for your new fix.

Best,

**Comment by MirkoAusFFM** [comment]
Sorry, my mistake. I tried again: with compiling. Here it works now.
(I hope the other file is automatically in the PR? Or please tell me, if I must open an new PR.)
Greetings

**Comment by khoih-prog** [comment]
> I hope the other file is automatically in the PR?)

No. And the change is also not correct

https://github.com/MirkoAusFFM/FTPClient_Generic/blob/846d7d05dfb86ac3b6eebb5474d20708e402a0b5/src/FTPClient_Generic.hpp#L146

> if I must open an new PR

Don't need to, just press `PR` again. If not OK, you can close and open a new PR.
Good exercise for you to master the PR process.

**Comment by MirkoAusFFM** [comment]
> Good exercise for you to master the PR process.

So true! xD
But it feels better now. (I hope it is!)
And thank you for your patience!

**Comment by khoih-prog** [comment]
I'd like your persistence, adventurous mind and willingness to accept and fix errors, which are the necessity in any field, especially in `embedded programming`. Keeping up the good works and you'll be much better.

Waiting for more of your PRs.

Merging this now.

Best Regards,

**Comment by MirkoAusFFM** [comment]
Thank you for merging and also the compliment. :-)
Greetings

**Comment by khoih-prog** [comment]
Hi @MirkoAusFFM 

The new [**FTPClient_Generic releases v1.5.0**](https://github.com/khoih-prog/FTPClient_Generic/releases/tag/v1.5.0) has just been published. Your contribution is noted in [**Contributions and Thanks**](https://github.com/khoih-prog/FTPClient_Generic#contributions-and-thanks)

Best Regards,

---

#### Releases v1.5.0

1. Add support to `RP2040W` with `CYW43439` WiFi using `arduino-pico` core

**Pull request merged**
